apiVersion: apps/v1
kind: Deployment
metadata:
  name: arm-rippers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arm-rippers
  template:
    metadata:
      labels:
        app: arm-rippers
    spec:
      containers:
        - name: arm-rippers
          image: registry.local/automaticrippingmachine/automatic-ripping-machine:latest
          resources:
            limits:
              amd.com/gpu: 1
          securityContext:
            privileged: true
            runAsUser: 0
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: home-arm
              mountPath: /home/arm
            - name: music
              mountPath: /home/arm/Music
            - name: logs
              mountPath: /home/arm/logs
            - name: media
              mountPath: /home/arm/media
            - name: config
              mountPath: /etc/arm/config
      volumes:
        - name: home-arm
          persistentVolumeClaim:
            claimName: arm-home
        - name: music
          persistentVolumeClaim:
            claimName: arm-music
        - name: logs
          persistentVolumeClaim:
            claimName: arm-logs
        - name: media
          persistentVolumeClaim:
            claimName: arm-media
        - name: config
          persistentVolumeClaim:
            claimName: arm-config