apiVersion: apps/v1
kind: Deployment
metadata:
  name: arm-rippers
spec:
  template:
    spec:
      initContainers:
        - name: fix-perms
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      containers:
        - name: arm-rippers
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "4"
              memory: 8Gi
              amd.com/gpu: 1
