apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: entertainment
resources:
- jellyfin.yaml
- storage.yaml
- namespace.yaml
- services.yaml
patches:
  - path: resources-patch.yaml