apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -o jellyfin.yaml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: jellyfin
  name: jellyfin
spec:
  ports:
    - name: "8096"
      port: 8096
      targetPort: 8096
    - name: "7359"
      port: 7359
      protocol: UDP
      targetPort: 7359
  selector:
    io.kompose.service: jellyfin
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - jellyfin.local
      secretName: jellyfin-tls
  rules:
  - host: jellyfin.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jellyfin
            port:
              number: 8096
---